name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize submodules
        run: git submodule update --init

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build-linux -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build-linux --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build-linux
        run: ctest -C ${{env.BUILD_TYPE}}

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize submodules
        run: git submodule update --init

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build-macos -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build-macos --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build-macos
        run: ctest -C ${{env.BUILD_TYPE}}

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize submodules
        run: git submodule update --init

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build-windows -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build-windows --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build-windows
        run: ctest -C ${{env.BUILD_TYPE}}