name: Build & Test
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  cpp-20-debug:
    name: C++ 20 (Debug)
    uses: karmakrafts/workflows/.github/workflows/cpp-quick.yml@master
    with:
      cmake_args: "-DKSTD_STREAMS_BUILD_TESTS=ON"
      build_type: "Debug"
      std_version: 20
